In [27]:
from sklearn.datasets import load_iris
import numpy as np
from sklearn.model_selection import train_test_split

In [29]:
iris=load_iris()

In [30]:
X=iris.data
y=iris.target

In [32]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.2,random_state=10)

In [35]:
#X_train.ndim
#X_test

In [36]:
from sklearn.linear_model import LogisticRegression

In [37]:
log=LogisticRegression()

In [38]:
log.fit(X_train,y_train)

c:\python37\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
c:\python37\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [42]:
y_test

array([1, 2, 0, 1, 0, 1, 1, 1, 0, 1, 1, 2, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2,
       2, 0, 1, 0, 1, 1, 1, 2])

In [43]:
pred=log.predict(X_test)

In [44]:
print(pred)

[1 2 0 1 0 1 2 1 0 1 2 2 1 0 0 2 2 0 0 0 2 2 2 0 1 0 1 1 1 2]


In [46]:
from sklearn.metrics import accuracy_score

In [48]:
accuracy_score(y_test,pred)

0.9

In [50]:
np.where(y_test!=pred)

(array([ 6, 10, 16], dtype=int64),)

In [51]:
c=log.coef_

In [52]:
c.shape

(3, 4)

In [59]:
#log.intercept_

In [60]:
log.intercept_[0]

0.25181938036271456

In [61]:
t=X_test[2].reshape(1,4)

In [62]:
y=np.dot(t,c.T)+log.intercept_[0]

In [63]:
y

array([[ 4.07363356, -2.43695937, -9.52052066]])

In [64]:
1/(1+np.exp(-y))

array([[9.83269232e-01, 8.03974309e-02, 7.33260964e-05]])

In [65]:
t.ndim

2

In [66]:
log.predict(t)

array([0])

In [68]:
y_test[2]

0